# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESjKgflE5tYqrFb61xNdr4Z3TF21gVsW
"""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os

def send_alert_email(sender_email, sender_password, receiver_email, subject, body, attachment_path):
    # Create a secure SSL context
    context = ssl.create_default_context()

    # Create the email
    message = MIMEMultipart()
    message["From"] = sender_email
    message["To"] = receiver_email
    message["Subject"] = subject

    # Add body to email
    message.attach(MIMEText(body, "html"))  # Use HTML format to support symbols

    # Attach file if provided
    if attachment_path and os.path.isfile(attachment_path):
        try:
            with open(attachment_path, "rb") as attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={os.path.basename(attachment_path)}",
                )
                message.attach(part)
        except Exception as e:
            print(f"Error attaching file: {e}")

    # Send the email
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.set_debuglevel(2)  # Enable more detailed debugging output
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, message.as_string())
            print("Email sent successfully!")
    except Exception as e:
        print(f"Error sending email: {e}")

# Prepare and send the email
if __name__ == "__main__":
    # Replace these variables with your actual details
    sender_email = "omdarekar4211@gmail.com"
    sender_password = "izls eage ipkp frcv"  # Use your App Password for Gmail
    receiver_email = "sauravbedse@gmail.com"

    # Specify the path to the file directly
    fraud_file_path = "/content/drive/MyDrive/fraudulent_transactions (2).csv"  # Update with your actual file path

    # Email subject and body
    subject = "🚨 Urgent: Suspicious Transactions Detected - Immediate Review Required 🚨"
    body = """
    <html>
    <body>
    <p>Dear Financial Security Officer,</p>
    <p><strong>🔍 Important Notice:</strong> Suspicious activities have been detected and require your immediate attention.</p>
    <p><strong>Summary of Alerts:</strong></p>
    <ul>
        <li>💰 <strong>High-Value Transactions:</strong> Transactions exceeding <strong>$10,000</strong> per week have been monitored for potential suspicious activity.</li>
        <li>🌍 <strong>High-Risk Countries:</strong> Alerts have been generated for transactions over <strong>$1,000</strong> from countries classified as high-risk.</li>
    </ul>
    <p><strong>Attachment:</strong></p>
    <ul>
        <li>📄 <strong>File Name:</strong> fraudulent_transactions (2).csv</li>
        <li>📋 <strong>Description:</strong> This file contains details of the flagged transactions for your review.</li>
    </ul>
    <p><strong>Action Required:</strong></p>
    <p>Please review the attached file and take the necessary actions, including investigating the transactions and considering account suspension if warranted.</p>
    <p>For further information or assistance, do not hesitate to contact me directly.</p>
    <p>Thank you for your prompt attention to this matter.</p>
    <p>Best regards,</p>
    <p>AML TEAM<br>
    <strong>Anti-Money Laundering (AML) Specialist</strong><br>
    SecureFinance Solutions<br>
    📧 amlteam@gmail.com<br>
    📞 +918767647450</p>
    </body>
    </html>
    """

    send_alert_email(sender_email, sender_password, receiver_email, subject, body, attachment_path=fraud_file_path)